name: Dependency Security Check

on:
  schedule:
    - cron: '0 0 * * *'  # 每天执行
  workflow_dispatch:

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=high

      - name: Create Fix Branch and PR
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="deps-fix-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH_NAME
          
          # 尝试修复依赖
          snyk fix --all-projects || true
          
          # 检查是否有更改
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # 提交更改
          git add .
          git commit -m "fix: 自动修复依赖安全漏洞"
          git push origin $BRANCH_NAME
          
          # 创建PR
          gh pr create \
            --title "fix: 修复依赖安全漏洞 $(date +%Y-%m-%d)" \
            --body "此PR由GitHub Actions自动创建，用于修复检测到的依赖安全漏洞。" \
            --base main \
            --head $BRANCH_NAME
